% %
% Simulation of C.Elegans network
% All cells (303 neurons), with only LeakConductance channel
% Synapses as in CElegans.net.nml (excitatory and inhibitory)
%
% Generic_GJ conductance changed from 1pS to 100 pS 
% (gap junction as in Kim2019, taken from Varshney2011)
%
% data_all: Forward Crawling Scenario: all cells, all synapses
%           - stimulus as in Kim2019: 1.4nA to PLM*, 2.3nA to AVB*
%           - should see response in most of the neurons
% data_all_noAVB: AVB* Ablation + Forward Crawling Scenario: 
%           - all cells except AVB*, all synapses except AVB* connected
%           - stimulus as in Kim2019: 1.4nA to PLM*, [2.3nA to AVB*]
%           - should see much smaller or even no response in most of the neurons
% data_all_noAVA: AVA* Ablation + Forward Crawling Scenario: 
%           - all cells except AVA*, all synapses except AVA* connected
%           - stimulus as in Kim2019: 1.4nA to PLM*, 2.3nA to AVB*
%           - should be similar to first scenario, response in most of the neurons
% data_all_IL2: Nictation Scenario: all cells, all synapses 
%           - stimulus as in Kim2019: 4.8nA to IL2DL/R, IL2L/R, IL2VL/R 
%           - should see response in neurons associated with head muscles,
%               but not large response for other neurons, such as those
%               associated with Forward Motion
% %

close all
clc
% clear all
% data_all = load('all_cells.dat');   % c302_D_Full.dat, all_cells.dat,
%                                     % all_cells_16out_400ms_dt0_1.dat
% data_all_noAVB = load('all_cells_noAVB.dat');
% data_all_noAVA = load('all_cells_noAVA.dat');
% data_all_IL2 = load('all_cells_IL2.dat');
% data_all_c302 = load('c302_D_Full.dat');

% % 
% % Positions in array data_all (missing from the next arrays, respectively):
% % AVBL: 57, AVBR: 58
% % AVAL: 55, AVAR: 56
% %
nrn = 'PHCL';
cells = readtable('all_cells_list.txt');
fprintf('\nThe networks is composed by: %i sensory neurons, %i interneurons, %i motor neurons)\n',...
    sum(contains(cells.CellType,'sensory')),...
    sum(contains(cells.CellType,'interneuron')),...
    sum(contains(cells.CellType,'motor')));

figure(18);
plot(...
    data_all(:,1),data_all(:,find(strcmp(cells.Cell,nrn)==1)+1),'-',...
    data_all_noAVB(:,1),data_all_noAVB(:,find(strcmp(cells.Cell,nrn)==1)+1),'-.',...
    data_all_noAVA(:,1),data_all_noAVA(:,find(strcmp(cells.Cell,nrn)==1)+1),'--',...
'LineWidth',2);
title({'Results simulation of C.Elegans network',...
    'Scenario: Forward Crawling.',['Neuron response: ',nrn]});
legend('Voltage recorded FM',...
    'Voltage recorded FM without AVB',...
    'Voltage recorded FM without AVA');
xlabel('Time [msec]'); ylabel('Voltage [mV]');
grid on;
set(gca,'FontSize',14);

% %
% % List the strongest responses (>100 mV)
% %
fprintf('\nCells with response over 100 mV in data_all (FM) = %i\n',...
    sum(max(data_all(:,2:end))>0.1));
fprintf('(%i sensory, %i interneurons, %i motor)\n',...
    sum(contains(cells.CellType(max(data_all(:,2:end))>0.1),'sensory')),...
    sum(contains(cells.CellType(max(data_all(:,2:end))>0.1),'interneuron')),...
    sum(contains(cells.CellType(max(data_all(:,2:end))>0.1),'motor')));

fprintf('\nCells with response over 100 mV in data_all_noAVB (FM without AVB) = %i\n',...
    sum(max(data_all_noAVB(:,2:end))>0.1));
fprintf('(%i sensory, %i interneurons, %i motor)\n',...
    sum(contains(cells.CellType(max(data_all_noAVB(:,2:end))>0.1),'sensory')),...
    sum(contains(cells.CellType(max(data_all_noAVB(:,2:end))>0.1),'interneuron')),...
    sum(contains(cells.CellType(max(data_all_noAVB(:,2:end))>0.1),'motor')));

fprintf('\nCells with response over 100 mV in data_all_noAVA (FM without AVA) = %i\n',...
    sum(max(data_all_noAVA(:,2:end))>0.1));
fprintf('(%i sensory, %i interneurons, %i motor)\n',...
    sum(contains(cells.CellType(max(data_all_noAVA(:,2:end))>0.1),'sensory')),...
    sum(contains(cells.CellType(max(data_all_noAVA(:,2:end))>0.1),'interneuron')),...
    sum(contains(cells.CellType(max(data_all_noAVA(:,2:end))>0.1),'motor')));


fprintf('\nListing of cells with response over 100 mV (data_all = FM):\n');
disp([cells.Cell(max(data_all(:,2:end))>0.1),...
    cells.CellType(max(data_all(:,2:end))>0.1)]);
fprintf('\nListing of cells with response over 100 mV (data_all_noAVB = FM without AVB):\n');
disp([cells.Cell(max(data_all_noAVB(:,2:end))>0.1),...
    cells.CellType(max(data_all_noAVB(:,2:end))>0.1)]);


fprintf('\nCells with response over 0 mV in data_all (FM) = %i\n',...
    sum(max(data_all(:,2:end))>0));
fprintf('(%i sensory, %i interneurons, %i motor)\n',...
    sum(contains(cells.CellType(max(data_all(:,2:end))>0),'sensory')),...
    sum(contains(cells.CellType(max(data_all(:,2:end))>0),'interneuron')),...
    sum(contains(cells.CellType(max(data_all(:,2:end))>0),'motor')));

fprintf('\nCells with response over 0 mV in data_all_noAVB (FM without AVB) = %i\n',...
    sum(max(data_all_noAVB(:,2:end))>0));
fprintf('(%i sensory, %i interneurons, %i motor)\n',...
    sum(contains(cells.CellType(max(data_all_noAVB(:,2:end))>0),'sensory')),...
    sum(contains(cells.CellType(max(data_all_noAVB(:,2:end))>0),'interneuron')),...
    sum(contains(cells.CellType(max(data_all_noAVB(:,2:end))>0),'motor')));

fprintf('\nCells with response over 0 mV in data_all_noAVA (FM without AVA) = %i\n',...
    sum(max(data_all_noAVA(:,2:end))>0));
fprintf('(%i sensory, %i interneurons, %i motor)\n',...
    sum(contains(cells.CellType(max(data_all_noAVA(:,2:end))>0),'sensory')),...
    sum(contains(cells.CellType(max(data_all_noAVA(:,2:end))>0),'interneuron')),...
    sum(contains(cells.CellType(max(data_all_noAVA(:,2:end))>0),'motor')));

% %
% % IL2
% %
% nrnIL2 = 'RMED';
% cells = readtable('all_cells_list.txt');

figure(20);
plot(...
    data_all(:,1),data_all(:,find(strcmp(cells.Cell,nrn)==1)+1),'-',...
    data_all_IL2(:,1),data_all_IL2(:,find(strcmp(cells.Cell,nrn)==1)+1),'--',...
'LineWidth',2);
title({'Results simulation of C.Elegans network',...
    'Scenario: Nictation.',['Neuron response: ',nrn]});
legend('Voltage recorded FM',...
    'Voltage recorded Nictation');
xlabel('Time [msec]'); ylabel('Voltage [mV]');
grid on;
set(gca,'FontSize',14);

% % %
% % % List the strongest responses (>100 mV)
% % %
% fprintf('\nCells with response over 100 mV in data_all (FM) = %i\n',...
%     sum(max(data_all(:,2:end))>0.1));
% fprintf('(%i sensory, %i interneurons, %i motor)\n',...
%     sum(contains(cells.CellType(max(data_all(:,2:end))>0.1),'sensory')),...
%     sum(contains(cells.CellType(max(data_all(:,2:end))>0.1),'interneuron')),...
%     sum(contains(cells.CellType(max(data_all(:,2:end))>0.1),'motor')));
% 
% fprintf('\nCells with response over 100 mV in data_all_IL2 (nictation) = %i\n',...
%     sum(max(data_all_IL2(:,2:end))>0.1));
% fprintf('(%i sensory, %i interneurons, %i motor)\n',...
%     sum(contains(cells.CellType(max(data_all_IL2(:,2:end))>0.1),'sensory')),...
%     sum(contains(cells.CellType(max(data_all_IL2(:,2:end))>0.1),'interneuron')),...
%     sum(contains(cells.CellType(max(data_all_IL2(:,2:end))>0.1),'motor')));
% 
% fprintf('\nListing of cells with response over 100 mV (data_all = FM):\n');
% disp([cells.Cell(max(data_all(:,2:end))>0.1),...
%     cells.CellType(max(data_all(:,2:end))>0.1)]);
% fprintf('\nListing of cells with response over 100 mV (data_all_IL2 = nictation):\n');
% disp([cells.Cell(max(data_all_IL2(:,2:end))>0.1),...
%     cells.CellType(max(data_all_IL2(:,2:end))>0.1)]);


% % %
% % % List the strongest responses (>500 mV)
% % %
% fprintf('\nCells with response over 500 mV in data_all (FM) = %i\n',...
%     sum(max(data_all(:,2:end))>0.5));
% fprintf('(%i sensory, %i interneurons, %i motor)\n',...
%     sum(contains(cells.CellType(max(data_all(:,2:end))>0.5),'sensory')),...
%     sum(contains(cells.CellType(max(data_all(:,2:end))>0.5),'interneuron')),...
%     sum(contains(cells.CellType(max(data_all(:,2:end))>0.5),'motor')));
% 
% fprintf('\nCells with response over 500 mV in data_all_IL2 (nictation) = %i\n',...
%     sum(max(data_all_IL2(:,2:end))>0.5));
% fprintf('(%i sensory, %i interneurons, %i motor)\n',...
%     sum(contains(cells.CellType(max(data_all_IL2(:,2:end))>0.5),'sensory')),...
%     sum(contains(cells.CellType(max(data_all_IL2(:,2:end))>0.5),'interneuron')),...
%     sum(contains(cells.CellType(max(data_all_IL2(:,2:end))>0.5),'motor')));
% 
% fprintf('\nListing of cells with response over 500 mV (data_all = FM):\n');
% disp([cells.Cell(max(data_all(:,2:end))>0.5),...
%     cells.CellType(max(data_all(:,2:end))>0.5)]);
% fprintf('\nListing of cells with response over 500 mV (data_all_IL2 = nictation):\n');
% disp([cells.Cell(max(data_all_IL2(:,2:end))>0.5),...
%     cells.CellType(max(data_all_IL2(:,2:end))>0.5)]);


