TITLE Mod file for component: Component(id=pulse_ramp_47_1 type=pulseGenerator)

COMMENT

    This NEURON file has been generated by org.neuroml.export (see https://github.com/NeuroML/org.neuroml.export)
         org.neuroml.export  v1.7.0
         org.neuroml.model   v1.7.0
         jLEMS               v0.10.2

ENDCOMMENT

NEURON {
    POINT_PROCESS pulse_ramp_47_1
    ELECTRODE_CURRENT i
    RANGE weight                            : property
    RANGE delay                             : parameter
    RANGE duration                          : parameter
    RANGE amplitude                         : parameter
    
}

UNITS {
    
    (nA) = (nanoamp)
    (uA) = (microamp)
    (mA) = (milliamp)
    (A) = (amp)
    (mV) = (millivolt)
    (mS) = (millisiemens)
    (uS) = (microsiemens)
    (molar) = (1/liter)
    (kHz) = (kilohertz)
    (mM) = (millimolar)
    (um) = (micrometer)
    (umol) = (micromole)
    (S) = (siemens)
    
}

PARAMETER {
    
    weight = 1
    delay = 0 (ms)
    duration = 50 (ms)
    durampmax = 50 (ms)
    stay0 = 50 (ms)
    amplitude = 1.4 (nA)
}

STATE {
    i (nA) 
    
}

INITIAL {
    rates()
    rates() ? To ensure correct initialisation.
    
}

BREAKPOINT {
    
    rates()
    if (t <  delay) {
        i = 0 ? standard OnCondition
    }
    
    if (t >=  delay  && t <  duration  +  delay) {
        i = weight  *  amplitude * (t-delay)/duration ? standard OnCondition
    }

    if (t >=  duration  +  delay  &&  t < delay + duration + durampmax) {
        i = weight  *  amplitude ? standard OnCondition
    }

    if (t >=  duration  +  delay  + durampmax && t < duration  +  delay  + durampmax + stay0) {
        i = 0 ? standard OnCondition
    }
    
    if (t >=  duration  +  delay  + durampmax + stay0 && t < 2*duration  +  delay  + durampmax + stay0) {
        i = weight  *  amplitude * (t-duration-delay-durampmax-stay0)/duration ? standard OnCondition
    }

    if (t >=  2*duration  +  delay  + durampmax + stay0 && t < 2*duration  +  delay  + 2*durampmax + stay0) {
        i = weight  *  amplitude ? standard OnCondition
    }

    if (t >=  2*duration  +  delay  + 2*durampmax + stay0 && t < 2*duration  +  delay  + 2*durampmax + 2*stay0) {
        i = 0 ? standard OnCondition
    }

    if (t >=  2*duration  +  delay  + 2*durampmax + 2*stay0 && t < 3*duration  +  delay  + 2*durampmax + 2*stay0) {
        i = weight  *  amplitude * (t-2*duration-delay-2*durampmax-2*stay0)/duration ? standard OnCondition
    }
    if (t >=  3*duration  +  delay  + 2*durampmax + 2*stay0 && t < 3*duration  +  delay  + 3*durampmax + 2*stay0) {
        i = weight  *  amplitude ? standard OnCondition
    }
    if (t >=  3*duration  +  delay  + 3*durampmax + 2*stay0) {
        i = 0 ? standard OnCondition
    }

}

PROCEDURE rates() {
    
    
     
    
}

